export const MODULE_NAME = 'core'

/* actions */
export const SET_AUTH_LOADER = `${MODULE_NAME}/SET_AUTH_LOADER`

export const LOGOUT_REQUEST = `${MODULE_NAME}/LOGOUT_REQUEST`
export const LOGOUT_SUCCESS = `${MODULE_NAME}/LOGOUT_SUCCESS`
export const LOGOUT_FAILURE = `${MODULE_NAME}/LOGOUT_FAILURE`

export const SET_SERVER_ERROR = `${MODULE_NAME}/SET_SERVER_ERROR`
export const RESET_SERVER_ERROR = `${MODULE_NAME}/RESET_SERVER_ERROR`
